[build]
  command = "yarn build"
  publish = "public"

[build.environment]
  # Fix for Sharp/libvips on Netlify
  SHARP_IGNORE_GLOBAL_LIBVIPS = "true"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "18.20.7"

[[plugins]]
  package = "@netlify/plugin-gatsby"
