backend:
  name: git-gateway

media_folder: "static/assets"
public_folder: "assets"

# Verkefni
collections:
  - name: "verkefni"
    label: "Verkefni"
    folder: "static/verkefni"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Lýsing", name: "lysing", widget: "text" }
      - { label: "Forsíðu mynd", name: "forsidu-mynd", widget: "image" }
